# Generated by Django 2.2.9 on 2020-01-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200122_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='video',
            name='media',
            field=models.FileField(upload_to='videos'),
        ),
    ]
