# Generated by Django 2.2.9 on 2020-01-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200122_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='theme',
        ),
        migrations.AddField(
            model_name='video',
            name='descr',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='themes',
            field=models.ManyToManyField(related_name='videos', to='core.Theme'),
        ),
    ]
