# Generated by Django 2.2.9 on 2020-01-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200123_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='core.Theme'),
        ),
    ]
